@baseUrl = http://localhost:5000/apis
@token = YOUR_JWT_HERE


#############################################
# STUDIOS - LISTAR TODOS
#############################################
GET {{baseUrl}}/v1/studios
Authorization: Bearer {{token}}


#############################################
# STUDIOS - DETALLE POR ID
#############################################
GET {{baseUrl}}/v1/studios/1
Authorization: Bearer {{token}}


#############################################
# STUDIOS - PELÍCULAS DEL STUDIO
#############################################
GET {{baseUrl}}/v1/studios/1/movies
Authorization: Bearer {{token}}


#############################################
# STUDIOS - CREAR STUDIO
#############################################
POST {{baseUrl}}/v1/studios
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Warner Bros",
  "country": "USA"
}


#############################################
# STUDIOS - OTRO EJEMPLO
#############################################
POST {{baseUrl}}/v1/studios
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Universal Pictures",
  "country": "USA"
}